-- RBAC/ownership migration for existing Supabase projects.
-- Run this once in Supabase SQL Editor if your tables were created
-- before role/ownerUserId were introduced.

alter table if exists public.users
  add column if not exists role text;

alter table if exists public.users
  add column if not exists "normalizedEmail" text;

update public.users
set "normalizedEmail" = lower(email)
where "normalizedEmail" is null;

alter table public.users
  alter column "normalizedEmail" set not null;

create unique index if not exists idx_users_normalized_email
  on public.users ("normalizedEmail");

alter table if exists public.users
  add column if not exists "isVerified" boolean not null default false;

alter table if exists public.users
  add column if not exists "otpHash" text;

alter table if exists public.users
  add column if not exists "otpExpiresAt" timestamptz;

alter table if exists public.users
  add column if not exists "otpLastSentAt" timestamptz;

alter table if exists public.users
  add column if not exists "otpAttempts" integer not null default 0;

alter table if exists public.users
  add column if not exists "resetTokenHash" text;

alter table if exists public.users
  add column if not exists "resetTokenExpiresAt" timestamptz;

alter table if exists public.users
  add column if not exists "resetLastSentAt" timestamptz;

alter table if exists public.users
  add column if not exists "createdIp" text;

alter table if exists public.users
  add column if not exists "profileImageUrl" text;

update public.users
set "isVerified" = true
where "isVerified" = false and "passwordHash" is not null;

update public.users
set role = 'user'
where role is null;

alter table public.users
  alter column role set default 'user';

alter table public.users
  alter column role set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_role_check'
  ) then
    alter table public.users
      add constraint users_role_check check (role in ('admin', 'user'));
  end if;
end $$;

alter table if exists public.items
  add column if not exists "ownerUserId" bigint null;

alter table if exists public.items
  add column if not exists "verificationPrompt" text null;

alter table if exists public.items
  add column if not exists "verificationAnswerHash" text null;

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  "itemId" uuid not null,
  "requesterUserId" bigint not null,
  "ownerUserId" bigint not null,
  message text null,
  "verificationResponse" text null,
  status text not null default 'pending',
  "ownerDecisionNote" text null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "resolvedAt" timestamptz null
);

update public.contact_requests
set status = 'pending'
where status is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'contact_requests_status_check'
  ) then
    alter table public.contact_requests
      add constraint contact_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'));
  end if;
end $$;

create index if not exists idx_items_owner_user_id
  on public.items ("ownerUserId");

create index if not exists idx_contact_requests_item_id
  on public.contact_requests ("itemId");

create index if not exists idx_contact_requests_owner_user_id
  on public.contact_requests ("ownerUserId");

create index if not exists idx_contact_requests_requester_user_id
  on public.contact_requests ("requesterUserId");
