-- Run this in Supabase SQL Editor before starting the app with DB_PROVIDER=supabase.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "firstName" text not null,
  "lastName" text not null,
  email text not null,
  "normalizedEmail" text not null unique,
  "passwordHash" text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  "isVerified" boolean not null default false,
  "otpHash" text null,
  "otpExpiresAt" timestamptz null,
  "otpLastSentAt" timestamptz null,
  "otpAttempts" integer not null default 0,
  "resetTokenHash" text null,
  "resetTokenExpiresAt" timestamptz null,
  "resetLastSentAt" timestamptz null,
  "createdIp" text null,
  "profileImageUrl" text null,
  "oauthProvider" text null,
  "oauthSubject" text null,
  "createdAt" timestamptz not null default now()
);

-- If your project created `users` before this column existed, run this (safe to re-run):
alter table public.users add column if not exists "profileImageUrl" text null;

alter table public.users add column if not exists "oauthProvider" text null;
alter table public.users add column if not exists "oauthSubject" text null;

create unique index if not exists idx_users_oauth_unique on public.users ("oauthProvider", "oauthSubject")
  where "oauthProvider" is not null and "oauthSubject" is not null;

create table if not exists public.items (
  id uuid primary key,
  title text not null,
  description text not null,
  category text not null,
  location text not null,
  date date not null,
  type text not null check (type in ('lost', 'found')),
  status text not null default 'active' check (status in ('active', 'claimed')),
  "contactName" text not null,
  "contactEmail" text not null,
  "ownerUserId" bigint null,
  "verificationPrompt" text null,
  "verificationAnswerHash" text null,
  "imagesJson" text null,
  "createdAt" timestamptz not null default now()
);

alter table public.items add column if not exists "imagesJson" text null;

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  "itemId" uuid not null,
  "requesterUserId" bigint not null,
  "ownerUserId" bigint not null,
  message text null,
  "verificationResponse" text null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled', 'closed')),
  "ownerDecisionNote" text null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "resolvedAt" timestamptz null
);

alter table public.contact_requests add column if not exists "threadTimelineJson" text null;

create table if not exists public.contact_request_messages (
  id bigint generated by default as identity primary key,
  "requestId" bigint not null,
  "authorUserId" bigint not null,
  body text not null,
  "attachmentUrl" text null,
  "createdAt" timestamptz not null default now()
);

create index if not exists idx_contact_request_messages_request on public.contact_request_messages ("requestId");

alter table public.contact_request_messages add column if not exists "attachmentUrl" text null;

create table if not exists public.contact_request_read_state (
  "requestId" bigint not null,
  "userId" bigint not null,
  "lastSeenAt" timestamptz not null default now(),
  primary key ("requestId", "userId")
);

create index if not exists idx_contact_request_read_state_user on public.contact_request_read_state ("userId");
